version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: no
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pgdb"
    ports:
      - "5432:5432"
  elasticsearch:
    image: bitnami/elasticsearch:latest
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=password
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  clickhouse:
    image: bitnami/clickhouse:latest
    ports:
      - "8123:8123"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - CLICKHOUSE_ADMIN_PASSWORD=admin
