version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: no
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pgdb"
    ports:
      - "5432:5432"